embeddings {
  tensor_name: "Product_Type:00120"
  metadata_path: "00120/Product_Type\\metadata.tsv"
  tensor_path: "00120/Product_Type\\tensors.tsv"
}
embeddings {
  tensor_name: "Store_Location:00120"
  metadata_path: "00120/Store_Location\\metadata.tsv"
  tensor_path: "00120/Store_Location\\tensors.tsv"
}
